export const quotes: string[] = [
  "A pet’s love is a gift that keeps on giving, always unconditional and pure. 🐾",
  "Adopting a pet is not just a choice, it’s a commitment to a life filled with companionship and joy. 🌟",
  "The bond between humans and their pets is one of the most beautiful things in the world. ❤️",
  "Pets make a house feel like a home, full of life, love, and warmth. 🏠",
  "The sound of a purring cat or a wagging dog’s tail can bring a sense of calm to the soul. 🐾",
  "Every pet deserves a loving home, and every home deserves the joy a pet brings. 🌈",
  "A pet can teach you patience, empathy, and the true meaning of unconditional love. 🐕",
  "The love and loyalty of a pet can lift your spirits and heal your heart. 💕",
  "Caring for a pet brings a sense of purpose, joy, and connection like nothing else. 🐾",
  "The simple presence of a pet can make a tough day a little easier. 😌",
  "A pet’s companionship can reduce stress, improve mood, and bring endless happiness. 😊",
  "No matter the breed or size, a pet’s heart is full of love waiting to be shared. 🐶🐱",
  "Pets offer the perfect reminder that the best things in life are often the simplest. 🌟",
  "A pet’s loyalty is a reflection of the love and care you give in return. 💖",
  "In every pet’s eyes, you see a world of love, trust, and friendship. 🐾",
  "Adopting a pet changes your life for the better, and their love is a constant source of joy. 🌟",
  "Pets don't need to speak to let you know how much they care, their presence says it all. 🐶🐱",
  "With every wag of the tail or purr of the cat, a pet makes life feel a little lighter. 🐾",
  "A home without a pet is missing one of life’s simplest and most rewarding joys. 🏡",
  "Pets bring out the best in us—offering companionship, comfort, and endless affection. 💕",
  "In the quiet moments, a pet’s companionship can be the most comforting presence. 🐾",
  "A pet’s love is the perfect reminder that true joy comes from giving, not receiving. ❤️",
  "The bond you share with a pet is built on love, trust, and mutual respect. 🐶🐱",
  "Pets never judge, they simply love and offer their heart freely. 💖",
  "Having a pet can be a source of peace and happiness, enriching your daily life. 🌿",
  "A pet’s presence can bring light into the darkest of days. ✨",
  "The companionship of a pet makes every moment a little brighter and every day a little better. ☀️",
  "Through thick and thin, a pet remains by your side, offering nothing but love. 🐾",
  "Pets offer a simple, yet powerful, reminder that life is better when shared with others. 💖",
  "The joy of having a pet lies in the small moments—the wag of a tail, the soft purr, the shared bond. 🐶🐱"
]
